create table if not exists public.service_content (
  locale text not null,
  section text not null,
  content text not null,
  primary key (locale, section)
);

create table if not exists public.service_images (
  id bigint generated by default as identity primary key,
  section text not null,
  url text not null,
  public_id text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists service_images_section_sort_order_idx
  on public.service_images (section, sort_order, created_at);
