import { randomUUID, createHash } from 'node:crypto';
import { prisma } from '@/lib/prisma';
import { createAuditEvent } from '@/lib/audit';
import { UUID_PATTERN } from '@/lib/attendance-exceptions';
import { buildCanonicalDailyBuckets, type CanonicalDailyBucketSegmentInput } from '@/lib/reporting/canonical-daily-buckets';

// docs/titanor-time/T8_REPORTS_DESIGN.md Addendum "T8.4B" — single owner of CSV_V1 generation,
// FULL/CORRECTION export-batch creation, and read access (list/detail/download). Every byte-format
// rule (§BG-BJ), population rule (§BA-BC), locking order (§BM), and audit/redaction rule (§BL/BN)
// documented there is implemented here, in one place, not scattered across route handlers.

// Deliberately NOT RepeatableRead (unlike the read-only T8.1-T8.3 report transactions, which never
// take a row lock or write). This transaction locks rows FOR UPDATE and then conditionally writes —
// the same shape as lib/periods.ts::lockPeriod and lib/corrections.ts::decideCorrection, both of
// which also run under Prisma/Postgres's plain default (READ COMMITTED), not RepeatableRead. Under
// RepeatableRead, a FOR UPDATE that blocks behind a concurrent writer and then unblocks against a
// row that writer just changed raises a real `40001 could not serialize access due to concurrent
// update` instead of just re-reading the fresh committed row — confirmed empirically by the two-
// concurrent-exporter tests (D37/D38) before this was found and fixed. READ COMMITTED is exactly
// the semantics this function's own "lock, then re-check the fresh state" steps (§BF) already
// assume.
const EXPORT_TX_OPTIONS = { maxWait: 10_000, timeout: 20_000 } as const;

const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

// ============================================================================
// §BG-BJ — CSV_V1 exact byte contract. Pure functions, no I/O.
// ============================================================================

const CSV_BOM = Buffer.from([0xef, 0xbb, 0xbf]);
const CRLF = '\r\n';

export const CSV_V1_COLUMNS = [
  'period_id',
  'period_start_date',
  'period_end_date',
  'export_batch_id',
  'export_kind',
  'employee_id',
  'employee_number',
  'employee_name',
  'site_id',
  'site_name',
  'date',
  'timesheet_version_id',
  'gross_minutes',
  'paid_break_minutes',
  'unpaid_break_minutes',
  'worked_minutes',
  'segment_count'
] as const;

// Indices of CSV_V1_COLUMNS that hold human-controlled text (employee_number, employee_name,
// site_name) — the only columns run through the formula-injection guard (§BI). UUID/date/integer/
// generated-metadata columns are never sanitized this way.
const HUMAN_TEXT_COLUMN_INDICES = new Set([6, 7, 9]);

// §BI — leading ASCII spaces only (not all whitespace) are skipped before checking the trigger
// character, because tab/CR/LF are themselves listed as distinct trigger characters, not absorbed
// into "leading whitespace".
const CSV_FORMULA_TRIGGER_RE = /^ *[=+\-@\t\r\n]/;

export function sanitizeHumanTextCell(value: string): string {
  return CSV_FORMULA_TRIGGER_RE.test(value) ? `'${value}` : value;
}

function escapeCell(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function buildCsvRow(cells: readonly (string | number)[]): string {
  const escaped = cells.map((cell, index) => {
    const raw = String(cell);
    const sanitized = HUMAN_TEXT_COLUMN_INDICES.has(index) ? sanitizeHumanTextCell(raw) : raw;
    return escapeCell(sanitized);
  });
  return escaped.join(',') + CRLF;
}

/** Builds the exact CSV_V1 bytes — BOM + header + zero or more data rows, every row (including the last) CRLF-terminated. `rows` must already be in final, deterministic order (§BH) — this function does not sort. */
export function buildCsvV1Content(rows: readonly (readonly (string | number)[])[]): Buffer {
  const header = buildCsvRow(CSV_V1_COLUMNS);
  const body = rows.map((row) => buildCsvRow(row)).join('');
  return Buffer.concat([CSV_BOM, Buffer.from(header + body, 'utf8')]);
}

// Node's global Uint8Array typing (@types/node) widens `new Uint8Array(n)` to
// Uint8Array<ArrayBufferLike>; Prisma's generated Bytes field type wants the narrower
// Uint8Array<ArrayBuffer> specifically (same ecosystem type gap already documented in
// lib/idempotency.ts's encryptResponseBody — the underlying buffer genuinely is a plain
// ArrayBuffer here, never a SharedArrayBuffer).
function toPrismaBytes(buffer: Buffer): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(buffer.byteLength);
  out.set(buffer);
  return out as Uint8Array<ArrayBuffer>;
}

function buildFileName(startDate: string, endDate: string, kind: 'FULL' | 'CORRECTION', batchId: string): string {
  return `titanor-time_${startDate}_${endDate}_${kind === 'FULL' ? 'full' : 'correction'}_${batchId}.csv`;
}

// §BH — deterministic ordering. Plain code-point (UTF-16 code unit) comparison — never
// localeCompare/Intl, which is locale- and runtime-dependent.
function compareBinary(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

interface ExportRowSortKey {
  employeeNumberSnapshot: string;
  employeeId: string;
  date: string;
  siteNameSnapshot: string;
  siteId: string;
}

function compareExportRows(a: ExportRowSortKey, b: ExportRowSortKey): number {
  return (
    compareBinary(a.employeeNumberSnapshot, b.employeeNumberSnapshot) ||
    compareBinary(a.employeeId, b.employeeId) ||
    compareBinary(a.date, b.date) ||
    compareBinary(a.siteNameSnapshot, b.siteNameSnapshot) ||
    compareBinary(a.siteId, b.siteId)
  );
}

// ============================================================================
// DTOs
// ============================================================================

export interface ExportBatchSummaryDto {
  id: string;
  periodId: string;
  format: 'CSV_V1';
  kind: 'FULL' | 'CORRECTION';
  correctsBatchId: string | null;
  fileName: string;
  fileHash: string;
  fileSizeBytes: number;
  rowCount: number;
  createdAt: string;
  downloadUrl: string;
}

function toSummaryDto(row: {
  id: string;
  periodId: string;
  format: string;
  kind: string;
  correctsBatchId: string | null;
  fileName: string;
  fileHash: string;
  fileSizeBytes: number;
  rowCount: number;
  createdAt: Date;
}): ExportBatchSummaryDto {
  return {
    id: row.id,
    periodId: row.periodId,
    format: row.format as 'CSV_V1',
    kind: row.kind as 'FULL' | 'CORRECTION',
    correctsBatchId: row.correctsBatchId,
    fileName: row.fileName,
    fileHash: row.fileHash,
    fileSizeBytes: row.fileSizeBytes,
    rowCount: row.rowCount,
    createdAt: row.createdAt.toISOString(),
    downloadUrl: `/api/admin/export-batches/${row.id}/download`
  };
}

const EXPORT_BATCH_SUMMARY_SELECT = {
  id: true,
  periodId: true,
  format: true,
  kind: true,
  correctsBatchId: true,
  fileName: true,
  fileHash: true,
  fileSizeBytes: true,
  rowCount: true,
  createdAt: true
} as const;

// ============================================================================
// §BF — POST /api/admin/periods/:periodId/export service.
// ============================================================================

export type CreateExportBatchError = { code: 'PERIOD_NOT_FOUND' } | { code: 'PERIOD_NOT_EXPORTABLE' } | { code: 'NOTHING_TO_EXPORT' };

export interface CreateExportBatchResult {
  batch: ExportBatchSummaryDto;
  period: { id: string; status: 'EXPORTED'; exportedAt: string };
  coveredCorrectionCount: number;
}

/**
 * §BF — one transaction. Lock order: PayrollPeriod -> Timesheet[] (ORDER BY id) -> (CORRECTION only)
 * CorrectionRequest[] (ORDER BY id) — §BM. Population (§BA) is exactly
 * PayrollPeriodParticipant.expected=true for this period, for both FULL and CORRECTION (a CORRECTION
 * batch is always a full replacement snapshot, never a delta, §BB). An expected participant without
 * a FINAL_APPROVED Timesheet + currentVersionId is an invariant failure (throw, never a silent skip
 * or partial batch) — period.lock already guarantees this for FULL, but this function re-verifies it
 * itself rather than trusting a fact proven at a different point in time (same TOCTOU-safe posture as
 * lib/periods.ts::lockPeriod's own re-check-under-the-lock).
 */
export async function createExportBatch(periodId: string, actorUserId: string, requestId: string): Promise<CreateExportBatchResult | CreateExportBatchError> {
  return prisma.$transaction(async (tx): Promise<CreateExportBatchResult | CreateExportBatchError> => {
    await tx.$queryRaw`SELECT id FROM "PayrollPeriod" WHERE id = ${periodId}::uuid FOR UPDATE`;
    const period = await tx.payrollPeriod.findUnique({ where: { id: periodId } });
    if (!period) {
      return { code: 'PERIOD_NOT_FOUND' };
    }
    if (period.status === 'OPEN') {
      return { code: 'PERIOD_NOT_EXPORTABLE' };
    }

    // §BA — population: exactly expected=true participants, for FULL and CORRECTION alike.
    const participants = await tx.payrollPeriodParticipant.findMany({ where: { periodId, expected: true }, select: { employeeId: true } });
    const expectedEmployeeIds = participants.map((p) => p.employeeId).sort();

    let kind: 'FULL' | 'CORRECTION';
    if (period.status === 'LOCKED') {
      kind = 'FULL';
    } else {
      // EXPORTED — §BC: eligibility is scoped to pending corrections belonging to expected
      // participants only (a correction on an excluded participant's timesheet can never be
      // represented in any snapshot, so it must never make a batch "needed" either).
      const pendingPeek = await tx.correctionRequest.count({
        where: { status: 'APPROVED', pendingExport: true, timesheet: { periodId, employeeId: { in: expectedEmployeeIds } } }
      });
      if (pendingPeek === 0) {
        return { code: 'NOTHING_TO_EXPORT' };
      }
      kind = 'CORRECTION';
    }

    // §BF step 3 / §BM — lock every expected participant's Timesheet row, ascending id, in one
    // statement (same idiom as lib/periods.ts::createPeriod's Employee lock).
    if (expectedEmployeeIds.length > 0) {
      await tx.$queryRaw`SELECT id FROM "Timesheet" WHERE "periodId" = ${periodId}::uuid AND "employeeId" = ANY(${expectedEmployeeIds}::uuid[]) ORDER BY id FOR UPDATE`;
    }
    const timesheets = await tx.timesheet.findMany({
      where: { periodId, employeeId: { in: expectedEmployeeIds } },
      select: { id: true, employeeId: true, status: true, currentVersionId: true }
    });
    const timesheetByEmployee = new Map(timesheets.map((t) => [t.employeeId, t]));
    for (const employeeId of expectedEmployeeIds) {
      const t = timesheetByEmployee.get(employeeId);
      if (!t || t.status !== 'FINAL_APPROVED' || !t.currentVersionId) {
        throw new Error(`EXPORT_INVARIANT_FAILURE: expected participant ${employeeId} lacks a FINAL_APPROVED timesheet with a currentVersionId (periodId=${periodId})`);
      }
    }

    // §BF step 4 / §BM — CORRECTION only: lock the eligible pending CorrectionRequest rows,
    // ascending id, then re-read their authoritative state under that lock (TOCTOU-safe, mirrors the
    // Timesheet re-check just above).
    let pendingCorrectionIds: string[] = [];
    if (kind === 'CORRECTION') {
      const candidateIds = (
        await tx.correctionRequest.findMany({
          where: { status: 'APPROVED', pendingExport: true, timesheet: { periodId, employeeId: { in: expectedEmployeeIds } } },
          select: { id: true },
          orderBy: { id: 'asc' }
        })
      ).map((c) => c.id);
      if (candidateIds.length > 0) {
        await tx.$queryRaw`SELECT id FROM "CorrectionRequest" WHERE id = ANY(${candidateIds}::uuid[]) ORDER BY id FOR UPDATE`;
      }
      const fresh = await tx.correctionRequest.findMany({
        where: { id: { in: candidateIds }, status: 'APPROVED', pendingExport: true },
        select: { id: true },
        orderBy: { id: 'asc' }
      });
      pendingCorrectionIds = fresh.map((c) => c.id);
      if (pendingCorrectionIds.length === 0) {
        return { code: 'NOTHING_TO_EXPORT' };
      }
    }

    // §BF step 6 — bulk, set-based reads. Zero queries inside any per-worker/per-day loop.
    const versionIds = timesheets.map((t) => t.currentVersionId!);
    const versionIdToEmployeeId = new Map(timesheets.map((t) => [t.currentVersionId!, t.employeeId]));

    const [employees, segments] = await Promise.all([
      expectedEmployeeIds.length > 0
        ? tx.employee.findMany({ where: { id: { in: expectedEmployeeIds } }, select: { id: true, employeeNumber: true, firstName: true, lastName: true } })
        : Promise.resolve([]),
      versionIds.length > 0
        ? tx.workSegment.findMany({
            where: { timesheetVersionId: { in: versionIds } },
            select: { timesheetVersionId: true, siteId: true, date: true, startAt: true, endAt: true, breaks: { select: { startAt: true, endAt: true, paid: true } } }
          })
        : Promise.resolve([])
    ]);
    const employeeById = new Map(employees.map((e) => [e.id, e]));

    // §BD — canonical (employeeId, siteId, date) bucket, shared with T8.3.
    const bucketInputs: CanonicalDailyBucketSegmentInput[] = segments.map((s) => ({
      employeeId: versionIdToEmployeeId.get(s.timesheetVersionId)!,
      timesheetVersionId: s.timesheetVersionId,
      siteId: s.siteId,
      date: s.date,
      startAt: s.startAt,
      endAt: s.endAt,
      breaks: s.breaks
    }));
    const buckets = buildCanonicalDailyBuckets(bucketInputs);

    const siteIds = [...new Set(buckets.map((b) => b.siteId))];
    const sites = siteIds.length > 0 ? await tx.workSite.findMany({ where: { id: { in: siteIds } }, select: { id: true, name: true } }) : [];
    const siteNameById = new Map(sites.map((s) => [s.id, s.name]));

    // §BF step 8 — batch id generated before CSV bytes, since it's embedded in every row.
    const batchId = randomUUID();
    const periodStartDate = formatDate(period.startDate);
    const periodEndDate = formatDate(period.endDate);

    interface RowRecord extends ExportRowSortKey {
      employeeNameSnapshot: string;
      timesheetVersionId: string;
      grossMinutes: number;
      paidBreakMinutes: number;
      unpaidBreakMinutes: number;
      workedMinutes: number;
      segmentCount: number;
    }

    const rowRecords: RowRecord[] = buckets.map((b) => {
      const emp = employeeById.get(b.employeeId)!;
      return {
        employeeId: b.employeeId,
        employeeNumberSnapshot: emp.employeeNumber,
        employeeNameSnapshot: `${emp.firstName} ${emp.lastName}`,
        siteId: b.siteId,
        siteNameSnapshot: siteNameById.get(b.siteId) ?? '',
        date: b.date,
        timesheetVersionId: b.timesheetVersionId!,
        grossMinutes: b.grossMinutes,
        paidBreakMinutes: b.paidBreakMinutes,
        unpaidBreakMinutes: b.unpaidBreakMinutes,
        workedMinutes: b.workedMinutes,
        segmentCount: b.segmentCount
      };
    });
    rowRecords.sort(compareExportRows);

    const csvRows = rowRecords.map((r) => [
      periodId,
      periodStartDate,
      periodEndDate,
      batchId,
      kind,
      r.employeeId,
      r.employeeNumberSnapshot,
      r.employeeNameSnapshot,
      r.siteId,
      r.siteNameSnapshot,
      r.date,
      r.timesheetVersionId,
      r.grossMinutes,
      r.paidBreakMinutes,
      r.unpaidBreakMinutes,
      r.workedMinutes,
      r.segmentCount
    ]);
    const content = buildCsvV1Content(csvRows);
    const fileHash = createHash('sha256').update(content).digest('hex');
    const fileSizeBytes = content.byteLength;
    const fileName = buildFileName(periodStartDate, periodEndDate, kind, batchId);
    const rowCount = rowRecords.length;

    let correctsBatchId: string | null = null;
    if (kind === 'CORRECTION') {
      const predecessor = await tx.exportBatch.findFirst({ where: { periodId }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], select: { id: true } });
      if (!predecessor) {
        throw new Error(`EXPORT_INVARIANT_FAILURE: EXPORTED period ${periodId} has no predecessor ExportBatch for a CORRECTION`);
      }
      correctsBatchId = predecessor.id;
    }

    const createdBatch = await tx.exportBatch.create({
      data: { id: batchId, periodId, format: 'CSV_V1', kind, createdByUserId: actorUserId, correctsBatchId, fileName, fileHash, fileSizeBytes, rowCount, content: toPrismaBytes(content) }
    });

    if (rowRecords.length > 0) {
      await tx.exportItem.createMany({
        data: rowRecords.map((r) => ({
          exportBatchId: batchId,
          employeeId: r.employeeId,
          timesheetVersionId: r.timesheetVersionId,
          siteId: r.siteId,
          date: new Date(`${r.date}T00:00:00.000Z`),
          employeeNumberSnapshot: r.employeeNumberSnapshot,
          employeeNameSnapshot: r.employeeNameSnapshot,
          siteNameSnapshot: r.siteNameSnapshot,
          grossMinutes: r.grossMinutes,
          paidBreakMinutes: r.paidBreakMinutes,
          unpaidBreakMinutes: r.unpaidBreakMinutes,
          workedMinutes: r.workedMinutes,
          segmentCount: r.segmentCount
        }))
      });
    }

    if (kind === 'CORRECTION' && pendingCorrectionIds.length > 0) {
      await tx.correctionRequest.updateMany({ where: { id: { in: pendingCorrectionIds } }, data: { coveredByExportBatchId: batchId, pendingExport: false } });
    }

    let exportedAt = period.exportedAt;
    if (kind === 'FULL') {
      const updatedPeriod = await tx.payrollPeriod.update({ where: { id: periodId }, data: { status: 'EXPORTED', exportedAt: new Date() } });
      exportedAt = updatedPeriod.exportedAt;
    }

    const coveredCorrectionCount = pendingCorrectionIds.length;

    // §BL — allowed AuditEvent fields only. No CSV content, no employee names/numbers, no
    // individual ExportItem, no correction reason, no GPS/device/payload/request data.
    await createAuditEvent(tx, {
      actorUserId,
      eventType: 'EXPORT_CREATED',
      entityType: 'EXPORT_BATCH',
      entityId: batchId,
      requestId,
      beforeValue: null,
      afterValue: { exportBatchId: batchId, periodId, format: 'CSV_V1', kind, correctsBatchId, rowCount, fileSizeBytes, fileHash, coveredCorrectionCount }
    });

    return {
      batch: {
        id: batchId,
        periodId,
        format: 'CSV_V1',
        kind,
        correctsBatchId,
        fileName,
        fileHash,
        fileSizeBytes,
        rowCount,
        createdAt: createdBatch.createdAt.toISOString(),
        downloadUrl: `/api/admin/export-batches/${batchId}/download`
      },
      period: { id: periodId, status: 'EXPORTED', exportedAt: exportedAt!.toISOString() },
      coveredCorrectionCount
    };
  }, EXPORT_TX_OPTIONS);
}

// ============================================================================
// §BK — read endpoints. Never mutate, never write an AuditEvent.
// ============================================================================

export interface PageQueryInput {
  page: string | null;
  pageSize: string | null;
}

export type PageQueryResult = { ok: true; page: number; pageSize: number } | { ok: false; fieldErrors: Record<string, string[]> };

export function parsePageQuery(input: PageQueryInput): PageQueryResult {
  const fieldErrors: Record<string, string[]> = {};

  let page = 1;
  if (input.page !== null && input.page !== '') {
    const parsed = Number(input.page);
    if (!Number.isInteger(parsed) || parsed < 1) {
      fieldErrors.page = ['must be a positive integer'];
    } else {
      page = parsed;
    }
  }

  let pageSize = DEFAULT_PAGE_SIZE;
  if (input.pageSize !== null && input.pageSize !== '') {
    const parsed = Number(input.pageSize);
    if (!Number.isInteger(parsed) || parsed < 1 || parsed > MAX_PAGE_SIZE) {
      fieldErrors.pageSize = [`must be an integer between 1 and ${MAX_PAGE_SIZE}`];
    } else {
      pageSize = parsed;
    }
  }

  if (Object.keys(fieldErrors).length > 0) {
    return { ok: false, fieldErrors };
  }
  return { ok: true, page, pageSize };
}

export function isValidExportBatchId(batchId: string): boolean {
  return UUID_PATTERN.test(batchId);
}

export interface ExportBatchListResult {
  items: ExportBatchSummaryDto[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

/** §BK GET /api/admin/export-batches — list, newest first, never includes `content`. */
export async function listExportBatches(filter: { periodId?: string }, pagination: { page: number; pageSize: number }): Promise<ExportBatchListResult> {
  const where = filter.periodId ? { periodId: filter.periodId } : {};
  const [totalItems, rows] = await Promise.all([
    prisma.exportBatch.count({ where }),
    prisma.exportBatch.findMany({
      where,
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      skip: (pagination.page - 1) * pagination.pageSize,
      take: pagination.pageSize,
      select: EXPORT_BATCH_SUMMARY_SELECT
    })
  ]);
  return {
    items: rows.map(toSummaryDto),
    page: pagination.page,
    pageSize: pagination.pageSize,
    totalItems,
    totalPages: Math.ceil(totalItems / pagination.pageSize)
  };
}

export interface ExportItemDto {
  id: string;
  employeeId: string;
  employeeNumberSnapshot: string;
  employeeNameSnapshot: string;
  siteId: string;
  siteNameSnapshot: string;
  date: string;
  timesheetVersionId: string;
  grossMinutes: number;
  paidBreakMinutes: number;
  unpaidBreakMinutes: number;
  workedMinutes: number;
  segmentCount: number;
}

export interface ExportBatchDetail {
  batch: ExportBatchSummaryDto;
  coveredCorrectionIds: string[];
  coveredCorrectionCount: number;
  items: ExportItemDto[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

/** §BK GET /api/admin/export-batches/:batchId — metadata + covered correction ids + paginated ExportItem DTO. Never includes `content` or correction reason/payload. */
export async function getExportBatchDetail(batchId: string, pagination: { page: number; pageSize: number }): Promise<ExportBatchDetail | null> {
  const batch = await prisma.exportBatch.findUnique({ where: { id: batchId }, select: EXPORT_BATCH_SUMMARY_SELECT });
  if (!batch) {
    return null;
  }

  const [coveredCorrections, totalItems, items] = await Promise.all([
    prisma.correctionRequest.findMany({ where: { coveredByExportBatchId: batchId }, select: { id: true }, orderBy: { id: 'asc' } }),
    prisma.exportItem.count({ where: { exportBatchId: batchId } }),
    prisma.exportItem.findMany({
      where: { exportBatchId: batchId },
      orderBy: [{ employeeNumberSnapshot: 'asc' }, { employeeId: 'asc' }, { date: 'asc' }, { siteNameSnapshot: 'asc' }, { siteId: 'asc' }],
      skip: (pagination.page - 1) * pagination.pageSize,
      take: pagination.pageSize,
      select: {
        id: true,
        employeeId: true,
        employeeNumberSnapshot: true,
        employeeNameSnapshot: true,
        siteId: true,
        siteNameSnapshot: true,
        date: true,
        timesheetVersionId: true,
        grossMinutes: true,
        paidBreakMinutes: true,
        unpaidBreakMinutes: true,
        workedMinutes: true,
        segmentCount: true
      }
    })
  ]);

  return {
    batch: toSummaryDto(batch),
    coveredCorrectionIds: coveredCorrections.map((c) => c.id),
    coveredCorrectionCount: coveredCorrections.length,
    items: items.map((i) => ({ ...i, date: formatDate(i.date) })),
    page: pagination.page,
    pageSize: pagination.pageSize,
    totalItems,
    totalPages: Math.ceil(totalItems / pagination.pageSize)
  };
}

export interface ExportBatchDownload {
  fileName: string;
  fileHash: string;
  fileSizeBytes: number;
  content: Buffer;
}

/** §BK GET /api/admin/export-batches/:batchId/download — exact stored bytes, never reconstructed. */
export async function getExportBatchDownload(batchId: string): Promise<ExportBatchDownload | null> {
  const batch = await prisma.exportBatch.findUnique({ where: { id: batchId }, select: { fileName: true, fileHash: true, fileSizeBytes: true, content: true } });
  if (!batch) {
    return null;
  }
  return { fileName: batch.fileName, fileHash: batch.fileHash, fileSizeBytes: batch.fileSizeBytes, content: Buffer.from(batch.content) };
}
