import { createHash, createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';

// docs/titanor-time/03_DATA_MODEL_ERD.md §4.1 + 04_ADMIN_FIRST_API_CONTRACTS.md §0.
// Callers only invoke this module when the client actually sent an
// `Idempotency-Key` header — the contract marks it "поддерживается", not
// mandatory, for endpoints like POST /api/admin/sites, so a route with no
// header just skips this module entirely and runs normally.

const IDEMPOTENCY_TTL_MS = 24 * 60 * 60 * 1000;
const GCM_IV_LENGTH = 12;
const GCM_AUTH_TAG_LENGTH = 16;

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidIdempotencyKeyFormat(value: string): boolean {
  return UUID_PATTERN.test(value);
}

/**
 * Deterministic hash of the parts of a request that define its target and
 * intent — path params (server-resolved, e.g. `{ siteId }`), relevant query,
 * and the parsed body. Object key order must not affect the hash, since two
 * functionally identical requests can arrive with differently-ordered JSON.
 */
export function computeRequestHash(parts: {
  pathParams?: Record<string, unknown>;
  query?: Record<string, unknown>;
  body?: unknown;
}): string {
  const canonical = canonicalize({
    pathParams: parts.pathParams ?? {},
    query: parts.query ?? {},
    body: parts.body ?? null
  });
  return createHash('sha256').update(canonical).digest('hex');
}

function canonicalize(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalize).join(',')}]`;
  }
  if (value !== null && typeof value === 'object') {
    const keys = Object.keys(value as Record<string, unknown>).sort();
    const entries = keys.map((key) => `${JSON.stringify(key)}:${canonicalize((value as Record<string, unknown>)[key])}`);
    return `{${entries.join(',')}}`;
  }
  return JSON.stringify(value);
}

function encryptionKey(): Buffer {
  const raw = process.env.IDEMPOTENCY_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error('IDEMPOTENCY_ENCRYPTION_KEY is not set.');
  }
  const key = Buffer.from(raw, 'base64');
  if (key.length !== 32) {
    throw new Error('IDEMPOTENCY_ENCRYPTION_KEY must decode to exactly 32 bytes (AES-256).');
  }
  return key;
}

// Returned as a plain Uint8Array<ArrayBuffer> (not Buffer<ArrayBufferLike>) to
// match Prisma's generated type for a Bytes column exactly — Buffer.concat's
// result has a wider ArrayBufferLike backing type that doesn't structurally
// satisfy it.
function encryptResponseBody(body: unknown): Uint8Array<ArrayBuffer> {
  const iv = randomBytes(GCM_IV_LENGTH);
  const cipher = createCipheriv('aes-256-gcm', encryptionKey(), iv);
  const plaintext = Buffer.from(JSON.stringify(body), 'utf8');
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const authTag = cipher.getAuthTag();
  const combined = Buffer.concat([iv, authTag, ciphertext]);
  // Node's global Uint8Array typing (@types/node) widens `new
  // Uint8Array(n)` to Uint8Array<ArrayBufferLike>; Prisma's generated Bytes
  // field type wants the narrower Uint8Array<ArrayBuffer> specifically. The
  // underlying buffer genuinely is a plain ArrayBuffer here (never a
  // SharedArrayBuffer), so this cast just corrects an ecosystem type gap,
  // not a real type hole.
  const out = new Uint8Array(combined.byteLength);
  out.set(combined);
  return out as Uint8Array<ArrayBuffer>;
}

function decryptResponseBody(stored: Uint8Array): unknown {
  const buffer = Buffer.from(stored);
  const iv = buffer.subarray(0, GCM_IV_LENGTH);
  const authTag = buffer.subarray(GCM_IV_LENGTH, GCM_IV_LENGTH + GCM_AUTH_TAG_LENGTH);
  const ciphertext = buffer.subarray(GCM_IV_LENGTH + GCM_AUTH_TAG_LENGTH);
  const decipher = createDecipheriv('aes-256-gcm', encryptionKey(), iv);
  decipher.setAuthTag(authTag);
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return JSON.parse(plaintext.toString('utf8'));
}

export interface IdempotencyIdentity {
  actorUserId: string;
  httpMethod: string;
  routeTemplate: string;
  idempotencyKey: string;
}

export type IdempotencyBeginResult =
  | { kind: 'PROCEED' }
  | { kind: 'CACHED'; statusCode: number; body: unknown }
  | { kind: 'CONFLICT'; code: 'IDEMPOTENCY_KEY_REUSED' | 'IDEMPOTENCY_KEY_IN_PROGRESS' };

/**
 * Call before executing the business logic. Returns PROCEED once — the
 * caller must then call completeIdempotentRequest() with the outcome,
 * whatever its status code, so the cached branches above have something to
 * return on a genuine retry. The PROCESSING row is inserted here, outside
 * any business transaction, so a concurrent second request with the same
 * key sees it immediately (the unique constraint is the actual race
 * serialization point, not this function's control flow).
 */
export async function beginIdempotentRequest(
  identity: IdempotencyIdentity,
  requestHash: string
): Promise<IdempotencyBeginResult> {
  try {
    await prisma.idempotencyKey.create({
      data: {
        actorUserId: identity.actorUserId,
        httpMethod: identity.httpMethod,
        routeTemplate: identity.routeTemplate,
        idempotencyKey: identity.idempotencyKey,
        requestHash,
        status: 'PROCESSING',
        expiresAt: new Date(Date.now() + IDEMPOTENCY_TTL_MS)
      }
    });
    return { kind: 'PROCEED' };
  } catch (err) {
    if (!(err instanceof Prisma.PrismaClientKnownRequestError) || err.code !== 'P2002') {
      throw err;
    }
  }

  const existing = await prisma.idempotencyKey.findUnique({
    where: {
      actorUserId_httpMethod_routeTemplate_idempotencyKey: {
        actorUserId: identity.actorUserId,
        httpMethod: identity.httpMethod,
        routeTemplate: identity.routeTemplate,
        idempotencyKey: identity.idempotencyKey
      }
    }
  });

  if (!existing) {
    // The row that caused P2002 above is gone by the time we read it back —
    // shouldn't happen (nothing in this codebase deletes IdempotencyKey
    // rows), not a state worth designing a recovery path for.
    throw new Error('IdempotencyKey unique violation but no matching row found.');
  }

  if (existing.status === 'PROCESSING') {
    return { kind: 'CONFLICT', code: 'IDEMPOTENCY_KEY_IN_PROGRESS' };
  }

  if (existing.requestHash !== requestHash) {
    return { kind: 'CONFLICT', code: 'IDEMPOTENCY_KEY_REUSED' };
  }

  return {
    kind: 'CACHED',
    statusCode: existing.statusCode ?? 500,
    body: existing.encryptedResponseBody ? decryptResponseBody(existing.encryptedResponseBody) : null
  };
}

/** Call once, after beginIdempotentRequest() returned PROCEED and the business logic has produced its final response. */
export async function completeIdempotentRequest(
  identity: IdempotencyIdentity,
  outcome: { statusCode: number; body: unknown }
): Promise<void> {
  await prisma.idempotencyKey.update({
    where: {
      actorUserId_httpMethod_routeTemplate_idempotencyKey: {
        actorUserId: identity.actorUserId,
        httpMethod: identity.httpMethod,
        routeTemplate: identity.routeTemplate,
        idempotencyKey: identity.idempotencyKey
      }
    },
    data: {
      status: 'COMPLETED',
      statusCode: outcome.statusCode,
      encryptedResponseBody: encryptResponseBody(outcome.body)
    }
  });
}
