import path from 'node:path';
import PDFDocument from 'pdfkit';
import type { ReportType } from '@/lib/report-files';
import { formatHelsinkiDateTime } from '@/lib/helsinki-datetime';

// docs/titanor-time/REPORT_REDESIGN_PRODUCTION_READINESS_RU.md §5 + §6 — every PDF/CSV produced by
// the new /admin/reports command centre is a WORKING report: an analytics snapshot, never the
// official payroll export (that stays in /admin/export, immutable ExportBatch/ExportItem). These
// documents are therefore:
//   * ENGLISH ONLY — title, headers, column names, statuses, units, footers, totals, warnings,
//     empty states, page numbers — regardless of the admin's UI language (§6).
//   * stamped with the banner below and a metadata block (period, status, generated at/by,
//     report type, filters) inside the file itself (§5.A).

export const WORKING_REPORT_BANNER = 'WORKING REPORT — NOT AN OFFICIAL PAYROLL EXPORT';

export const REPORT_TYPE_NAME: Record<ReportType, string> = {
  PERIOD_SUMMARY: 'Payroll period summary',
  SITE_DETAIL: 'Site detail',
  WORKER_DETAIL: 'Worker detail'
};

export const REPORT_TYPE_DESCRIPTION: Record<ReportType, string> = {
  PERIOD_SUMMARY: 'Company-wide hours and timesheet status for one payroll period, one row per site.',
  SITE_DETAIL: 'Every worker on one site for one payroll period, with per-worker hours and timesheet status.',
  WORKER_DETAIL: 'One worker across every site for one payroll period, with per-site hours.'
};

export interface WorkingReportMeta {
  reportType: ReportType;
  periodLabel: string;
  periodStatus: string; // OPEN | LOCKED | EXPORTED — already English
  generatedAtIso: string;
  generatedBy: string;
  filters: string[];
}

/** "12 h 30 min" — English, always. Never the locale-aware formatWorkedDuration. */
export function formatMinutesEnglish(minutes: number): string {
  const safe = Number.isFinite(minutes) ? Math.max(0, Math.round(minutes)) : 0;
  return `${Math.floor(safe / 60)} h ${safe % 60} min`;
}

const TIMESHEET_STATUS_EN: Record<string, string> = {
  DRAFT: 'Draft',
  SUBMITTED: 'Submitted',
  RETURNED: 'Returned',
  FOREMAN_APPROVED: 'Review approved',
  FINAL_APPROVED: 'Final approved'
};

export function timesheetStatusEnglish(status: string | null | undefined): string {
  if (!status) return 'No timesheet';
  return TIMESHEET_STATUS_EN[status] ?? status;
}

/** The metadata rows every working report prints, as [label, value] pairs (§5.A). */
export function metaRows(meta: WorkingReportMeta): [string, string][] {
  return [
    ['Report type', `${REPORT_TYPE_NAME[meta.reportType]} (${meta.reportType})`],
    ['Payroll period', meta.periodLabel],
    ['Period status', meta.periodStatus],
    ['Generated at', formatHelsinkiDateTime(meta.generatedAtIso)],
    ['Generated by', meta.generatedBy],
    ['Included filters', meta.filters.length > 0 ? meta.filters.join('; ') : 'None']
  ];
}

// ── CSV ────────────────────────────────────────────────────────────────────────────────────────

/** The banner + metadata block that opens every working-report CSV, before the data header row.
 * Each line is one already-escaped CSV row (via buildCsvRow at the call site is unnecessary — these
 * are fixed ASCII), terminated with CRLF to match buildCsvRow. */
export function csvMetaBlock(meta: WorkingReportMeta): string[] {
  const rows: string[] = [`"${WORKING_REPORT_BANNER}"\r\n`];
  for (const [label, value] of metaRows(meta)) {
    rows.push(`"${label}","${value.replace(/"/g, '""')}"\r\n`);
  }
  rows.push('\r\n'); // blank separator line
  return rows;
}

// ── PDF ────────────────────────────────────────────────────────────────────────────────────────

const FONT_REGULAR_PATH = path.join(process.cwd(), 'assets/fonts/DejaVuSans.ttf');
const FONT_BOLD_PATH = path.join(process.cwd(), 'assets/fonts/DejaVuSans-Bold.ttf');

export function newWorkingReportPdf(layout: 'portrait' | 'landscape' = 'portrait'): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: 'A4',
    layout,
    margins: { top: 46, bottom: 44, left: 40, right: 40 },
    bufferPages: true,
    autoFirstPage: true
  });
  doc.registerFont('DejaVu', FONT_REGULAR_PATH);
  doc.registerFont('DejaVu-Bold', FONT_BOLD_PATH);
  doc.font('DejaVu').fillColor('#111111');
  return doc;
}

/** Title + banner + metadata block. Returns the Y coordinate the caller should continue drawing at. */
export function drawWorkingReportHeader(doc: PDFKit.PDFDocument, title: string, meta: WorkingReportMeta): number {
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.font('DejaVu-Bold').fontSize(16).fillColor('#111111').text('TITANOR TIME', left, doc.page.margins.top);
  doc.font('DejaVu-Bold').fontSize(12).text(title, { width });
  doc.moveDown(0.3);
  doc.font('DejaVu-Bold').fontSize(8).fillColor('#8a1c1c').text(WORKING_REPORT_BANNER, { width });
  doc.moveDown(0.5);

  doc.font('DejaVu').fontSize(8).fillColor('#333333');
  for (const [label, value] of metaRows(meta)) {
    doc.font('DejaVu-Bold').text(`${label}: `, { continued: true }).font('DejaVu').text(value);
  }
  doc.moveDown(0.6);
  doc.fillColor('#111111');
  return doc.y;
}

export interface WorkingReportColumn {
  header: string;
  width: number;
  align?: 'left' | 'right';
}

/** Draws a paginated table: repeats the header row on every page break, optional bold TOTAL row,
 * optional empty-state text. Returns the Y coordinate after the table. Page numbers are the
 * caller's job (drawWorkingReportPageNumbers, once, at the end). */
export function drawWorkingReportTable(
  doc: PDFKit.PDFDocument,
  startY: number,
  columns: WorkingReportColumn[],
  rows: string[][],
  opts: { totalRow?: string[]; emptyText?: string } = {}
): number {
  const left = doc.page.margins.left;
  const totalWidth = columns.reduce((a, c) => a + c.width, 0);
  const bottomLimit = doc.page.height - doc.page.margins.bottom;
  let y = startY;

  const drawHead = (top: number): number => {
    doc.rect(left, top, totalWidth, 20).fillAndStroke('#eeeeee', '#333333');
    doc.fillColor('#111111').font('DejaVu-Bold').fontSize(7.5);
    let cx = left;
    for (const col of columns) {
      doc.text(col.header, cx + 3, top + 6, { width: col.width - 6, align: col.align ?? 'left', lineBreak: false });
      cx += col.width;
    }
    return top + 20;
  };

  const drawRow = (cells: string[], bold = false): void => {
    const heights = columns.map((col, i) => doc.heightOfString(cells[i] ?? '', { width: col.width - 6 }));
    const rowHeight = Math.max(18, ...heights) + 6;
    if (y + rowHeight > bottomLimit) {
      doc.addPage();
      y = drawHead(doc.page.margins.top);
    }
    doc.rect(left, y, totalWidth, rowHeight).stroke('#cccccc');
    doc.font(bold ? 'DejaVu-Bold' : 'DejaVu').fontSize(7.5).fillColor('#111111');
    let cx = left;
    for (let i = 0; i < columns.length; i++) {
      doc.text(cells[i] ?? '', cx + 3, y + 4, { width: columns[i].width - 6, align: columns[i].align ?? 'left' });
      cx += columns[i].width;
    }
    y += rowHeight;
  };

  y = drawHead(y);
  if (rows.length === 0) {
    drawRow([opts.emptyText ?? 'No rows.']);
  } else {
    for (const row of rows) drawRow(row);
    if (opts.totalRow) drawRow(opts.totalRow, true);
  }
  return y;
}

export function drawWorkingReportPageNumbers(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const { width, height } = doc.page;
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc.font('DejaVu').fontSize(7).fillColor('#666666');
    doc.text(`Page ${i + 1} of ${range.count}`, 0, height - savedBottom + 14, { width, align: 'center', lineBreak: false });
    doc.fillColor('#111111');
    doc.page.margins.bottom = savedBottom;
  }
}

export function finalizeWorkingReportPdf(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

// ── file names ─────────────────────────────────────────────────────────────────────────────────
// Only characters allowed by CK-58 (`^[A-Za-z0-9._ -]{1,255}$`).

function slugPart(raw: string): string {
  return raw.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'x';
}

export function workingReportFileName(
  reportType: ReportType,
  format: 'PDF' | 'CSV',
  parts: { startDate: string; endDate: string; subject?: string }
): string {
  const kind = reportType === 'PERIOD_SUMMARY' ? 'period' : reportType === 'SITE_DETAIL' ? 'site' : 'worker';
  const subject = parts.subject ? `_${slugPart(parts.subject)}` : '';
  return `titanor-working-report_${kind}${subject}_${parts.startDate}_${parts.endDate}.${format.toLowerCase()}`;
}
